export const SET_LOADING = "SET_LOADING";

export const SELECT_WORKSPACE = "SELECT_WORKSPACE";
export const WORKSPACE_SELECTED = "WORKSPACE_SELECTED";
export const WORKSPACE_DESELECTED = "WORKSPACE_DESELECTED";

export const TRAININGS_FETCH_REQUESTED = "TRAININGS_FETCH_REQUESTED";
export const TRAININGS_FETCH_SUCCEEDED = "TRAININGS_FETCH_SUCCEEDED";
export const TRAININGS_FETCH_FAILED = "TRAININGS_FETCH_FAILED";
